### PR TITLE
fix: make delay queue release expired messages immediately

### PR DESCRIPTION
**Pull request by arealmaas**
Related to #DIF-2878 - https://edtechfoundry.atlassian.net/browse/DIF-2878

When a message fails, the retry-lib will specify a expiration and put the message in a delay queue. When the message expires, the message will be put back into the original queue. If the message fails again, the expiration will increase with (Math.pow(2, retryCount) * 1000) ms. But, the queues in rabbitmq are FIFO, which means that if there are multiple messages that have a expiration of 5 mins in front of a message that has a expiration of 100ms, the last message will not be retried until 5 min has gone by... ¯_(ツ)_/¯ So in order for messages to be retried when they are supposed to, we would have to create a delay-queue per retry-count. This way we can ensure that the messages will be delivered when they are supposed to as the messages will have an equal amount of delay.

---
This change is [Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)

### CODE REVIEW

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/initializer.js, line 12 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS0rq30NPFB5GiDljS:-LKS0GXJEA0cGeAc5-6O:blt6l9v) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/initializer.js#L12)):*
> ```JavaScript
> 
>   assertDelayQueues(retryCount) {
>     const assertQueuePromiseMap = new Array(retryCount).map(c =>
> ```

instead of new Array and map, just use a for each loop? I do not think this will work as expected. The c will be void AFAIK as the second parameter is the index

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/initializer.js, line 12 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS0rq30NPFB5GiDljS:-LKS1XQF4c39XQ6FAcf0:b-lp3l1v) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/initializer.js#L12)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

instead of new Array and map, just use a for each loop? I do not think this will work as expected. The c will be void AFAIK as the second parameter is the index
</blockquote></details>

I'm not even sure it will loop in its current state?

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/amqp_handler_wrapper.js, line 59 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS1ql35_SbeqfhC9_0:-LKS1ql35_SbeqfhC9_1:b-1z0ssm) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/amqp_handler_wrapper.js#L59)):*
> ```JavaScript
>     return channel.publish(
>       '',
>       `${config.delayQueueName}-${msg.properties.headers._retryCount}`,
> ```

I'm not sure this works as expected? Should it not create a queue for the time it should wait, not the number of retries? Confused

**Review by arealmaas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/amqp_handler_wrapper.js, line 59 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS1ql35_SbeqfhC9_0:-LKS2Br16a0XZoRbMBo2:b-pow67t) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/amqp_handler_wrapper.js#L59)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I'm not sure this works as expected? Should it not create a queue for the time it should wait, not the number of retries? Confused
</blockquote></details>

Yeah, if we decide to ship another delay, then it would be fucked. So yeah, just changing to using the delay function instead

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/initializer.js, line 12 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS0rq30NPFB5GiDljS:-LKS7deu9brI-KrT2-ZG:bwe5nyr) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/initializer.js#L12)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I'm not even sure it will loop in its current state?
</blockquote></details>

still not responded to this tho. Tried running new Array(10).map(c=>console.log(c)); locally? I did, did not look like this would work?

**Review by arealmaas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/amqp_handler_wrapper.js, line 59 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS1ql35_SbeqfhC9_0:-LKS5WgU447jlnQmEUo2:b-896fix) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/amqp_handler_wrapper.js#L59)):*
<details><summary><i>Previously, AlmaasAre (Are Almaas) wrote…</i></summary><blockquote>

Yeah, if we decide to ship another delay, then it would be fucked. So yeah, just changing to using the delay function instead
</blockquote></details>

Done.
___
*[src/initializer.js, line 12 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS0rq30NPFB5GiDljS:-LKSGj3m23iC2Na49852:b-2hgub) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/initializer.js#L12)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

still not responded to this tho. Tried running new Array(10).map(c=>console.log(c)); locally? I did, did not look like this would work?
</blockquote></details>

Yeah, hah, not sure what I was thinking here

**Review by arealmaas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/initializer.js, line 12 at r1](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKS0rq30NPFB5GiDljS:-LKSMDym3m_aAoL-7E54:b-896fix) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/57cc66b4897c0557561a0f2482b60b5d4e86cc0c/src/initializer.js#L12)):*
<details><summary><i>Previously, AlmaasAre (Are Almaas) wrote…</i></summary><blockquote>

Yeah, hah, not sure what I was thinking here
</blockquote></details>

Done.

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/index.js, line 9 at r3](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKSP-ZHAaDoDPsvKzu6:-LKSP-ZHAaDoDPsvKzu7:b-6mybg8) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/91d5f9da71dbb47c1e5f6c13b8e336a307adb1e0/src/index.js#L9)):*
> ```JavaScript
>   const delay = Math.pow(2, attempts);
>   if (delay > 60 * 60 * 24) {
>     // the delay for the message is longer than 24 hours.  Fail the message and never retry again.
> ```

throw?

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/index.js, line 9 at r3](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKSP-ZHAaDoDPsvKzu6:-LKSQ0440RgEQKPpMOea:b-e90rlx) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/91d5f9da71dbb47c1e5f6c13b8e336a307adb1e0/src/index.js#L9)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

nope, throw?
</blockquote></details>

and/or log?

**Review by arealmaas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/index.js, line 9 at r3](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKSP-ZHAaDoDPsvKzu6:-LKW3d-f8GV66S7a1gJ_:bhvvpty) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/91d5f9da71dbb47c1e5f6c13b8e336a307adb1e0/src/index.js#L9)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

and/or log?
</blockquote></details>

We want to send the message to the failed queue here if it's longer, so cannot throw. Unless it's caught someplace. But logging error instead

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/get_default_delay.js, line 6 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWefBM0KVZdtlAfXst:-LKWefBM0KVZdtlAfXsu:b-uhi05) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/src/get_default_delay.js#L6)):*
> ```JavaScript
>   if (delay > 60 * 60 * 24) {
>     console.error(
>       'the delay for the message is longer than 24 hours.  Fail the message and never retry again.'
> ```

The message will be discarded and never retried

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/get_default_delay.js, line 3 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWerfG2v0ToFpX2V-v:-LKWerfG2v0ToFpX2V-w:b-q1zri3) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/src/get_default_delay.js#L3)):*
> ```JavaScript
> // attempts must be a number in milliseconds
> module.exports = attempts => {
>   const delay = Math.pow(2, attempts);
> ```

times 1000 here instead of at the return? 

Kind of confusing to mix it. 

const MAX = 24 * 60 * 60 * 1000; // 24 hours

delay = (2^attempts) * 1000;

if delay > MAX

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/get_default_delay.js, line 2 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWfNPI2YDT_FNVXtd1:-LKWfNPI2YDT_FNVXtd2:baqn3u4) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/src/get_default_delay.js#L2)):*
> ```JavaScript
> // attempts must be a number in milliseconds
> module.exports = attempts => {
> ```

I would prefer a named function here for traceability and searchability

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/get_default_delay.js, line 6 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWefBM0KVZdtlAfXst:-LKWfi-P3_N-pYgYGdhU:bs85dmj) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/src/get_default_delay.js#L6)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

The message will be discarded and never retried
</blockquote></details>

just make it clear it is failed. Now it sounds like it is asking to fail it

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[test/index.js, line 26 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWg21NCO74d-kN97qD:-LKWg21NCO74d-kN97qE:bchiq2q) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/test/index.js#L26)):*
> ```JavaScript
>     return Promise.all([
>       channel.checkQueue(ENTRY_QUEUE_NAME),
>       channel.checkQueue(getDelayQueueName(DELAY_QUEUE_NAME, retryAttempt, delayFn)),
> ```

I think using a constant here is better for testing that the queue name is as expected (getDelayQueueName might have a bug but we won't catch it)

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[test/index.js, line 14 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWgKMJ2FKMrFbVE6u_:-LKWgKMJ2FKMrFbVE6ua:b-qe4qgo) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/test/index.js#L14)):*
> ```JavaScript
> const FAILURE_QUEUE_NAME = 'amqplib-retry.tests.failure';
> const CONSUMER_TAG = 'amqplib-retry.tests';
> ```

add DELAY_QUEUE_NAME here?

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[test/index.js, line 14 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWgKMJ2FKMrFbVE6u_:-LKWghWZBrnQZQDAb7Mo:bssadhd) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/test/index.js#L14)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

add DELAY_QUEUE_NAME here?
</blockquote></details>

or an array? Not sure

**Review by kennethlynne — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[test/index.js, line 165 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWgkut0tobyfEtjdvq:-LKWgkut0tobyfEtjdvr:b-ylkgqr) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/test/index.js#L165)):*
> ```JavaScript
>       .delay(1000) // enough time for at least four iterations
>       .then(() => {
>         console.log('callcount: ', spy.callCount);
> ```

not sure this should get in here

**Review by arealmaas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2)* status: 0 of 2 LGTMs obtained

___
*[src/get_default_delay.js, line 2 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWfNPI2YDT_FNVXtd1:-LKXk4J9D4sjOsAkHodA:b-896fix) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/src/get_default_delay.js#L2)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I would prefer a named function here for traceability and searchability
</blockquote></details>

Done.
___
*[src/get_default_delay.js, line 3 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWerfG2v0ToFpX2V-v:-LKXkFRhAvp3rAu216HJ:b-896fix) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/src/get_default_delay.js#L3)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

times 1000 here instead of at the return? 

Kind of confusing to mix it. 

const MAX = 24 * 60 * 60 * 1000; // 24 hours

delay = (2^attempts) * 1000;

if delay > MAX
</blockquote></details>

Done.
___
*[src/get_default_delay.js, line 6 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWefBM0KVZdtlAfXst:-LKXkOfoDnJM3GEOgGMD:b-896fix) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/src/get_default_delay.js#L6)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

just make it clear it is failed. Now it sounds like it is asking to fail it
</blockquote></details>

Done.
___
*[test/index.js, line 14 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWgKMJ2FKMrFbVE6u_:-LKXfPsY49pIzdh9HOKc:b-f4hoe2) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/test/index.js#L14)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

or an array? Not sure
</blockquote></details>

the name depends on what parameter you pass. This test uses a rabbitmq connection, so the code will create different delay queues based on the current retry-attempt. Some of the tests have more than one retry, so the queue will be named differently
___
*[test/index.js, line 26 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWg21NCO74d-kN97qD:-LKXeru307jklshxHG5k:bhwf6mm) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/test/index.js#L26)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I think using a constant here is better for testing that the queue name is as expected (getDelayQueueName might have a bug but we won't catch it)
</blockquote></details>

Not quite sure what you mean. Using a fixed string as the delay queue name?
___
*[test/index.js, line 165 at r4](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-LKWgkut0tobyfEtjdvq:-LKXerJ524PyQ-6tnQn5:b-896fix) ([raw file](https://github.com/edtechfoundry/node-amqplib-retry/blob/46b524e1136e756fb1601a6f895e311c8684f1b4/test/index.js#L165)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

not sure this should get in here
</blockquote></details>

Done.

**Review by kennethlynne — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/edtechfoundry/node-amqplib-retry/2#-:-LKXveVj-FH1QCk2PIAe:bg7igkv)* status: 0 of 2 LGTMs obtained, and 1 stale

**Pull request merged**
